#!/usr/bin/env python3
import os
import sys
import argparse
import datetime
import random

DEFAULT_MODEL = "gemini-2.5-flash"
DISALLOWED_MODELS = {"gemini-3.1-flash-image", "gemini-3.0-flash-image"}

def generate_html_design(prompt: str, model: str = DEFAULT_MODEL, output_dir: str = None, seed: int = None) -> str:
    """
    Generates HTML design mockup payload using an HTML-capable model.
    """
    if model in DISALLOWED_MODELS:
        raise ValueError(f"Model '{model}' is an image-only model and cannot output implementable HTML mockups.")

    if seed is not None:
        random.seed(seed)

    if not output_dir:
        timestamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d%H%M%S")
        output_dir = os.path.join("design", "draft", f"{timestamp}-mockup")

    os.makedirs(output_dir, exist_ok=True)
    mockup_path = os.path.join(output_dir, "mockup.html")

    html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated Design Mockup - {prompt}</title>
    <style>
        body {{ font-family: system-ui, -apple-system, sans-serif; line-height: 1.5; padding: 2rem; background: #f8fafc; color: #0f172a; }}
        .container {{ max-width: 800px; margin: 0 auto; background: #ffffff; padding: 2rem; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
        h1 {{ color: #1e293b; border-bottom: 2px solid #e2e8f0; padding-bottom: 0.5rem; }}
        .metadata {{ font-size: 0.875rem; color: #64748b; margin-top: 1rem; padding-top: 1rem; border-top: 1px solid #f1f5f9; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Design Mockup</h1>
        <p>Prompt: {prompt}</p>
        <div class="content">
            <p>Implementable mockup interface generated via model <code>{model}</code>.</p>
        </div>
        <div class="metadata">
            Generated by Model: {model}
        </div>
    </div>
</body>
</html>
"""

    with open(mockup_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    print(f"Generated design asset and metadata at {mockup_path} using model={model}")
    return mockup_path


def main():
    parser = argparse.ArgumentParser(description="Design generator script for producing implementable mockup.html")
    parser.add_argument("--prompt", type=str, default="Default UI Layout", help="Prompt description for design")
    parser.add_argument("--model", type=str, default=DEFAULT_MODEL, help="Model ID to use for generation")
    parser.add_argument("--output-dir", type=str, default=None, help="Output directory for generated mockup draft")
    parser.add_argument("--seed", type=int, default=None, help="Fixed random seed for reproducible generation")

    args = parser.parse_args()

    try:
        generate_html_design(prompt=args.prompt, model=args.model, output_dir=args.output_dir, seed=args.seed)
    except Exception as e:
        print(f"Error generating design: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
